### ISSUE TITLE
domain NOTFOUND

### ISSUE THREAD

**Issue by vladare** [okTurtles/dnschain#157] opened 2015-05-07 19:05 UTC
No domain found in command response. Here is the command and debug log

dig @localhost -p 5333 freespeechme.bit

; <<>> DiG 9.9.5-3ubuntu0.2-Ubuntu <<>> @localhost -p 5333 freespeechme.bit
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 53062
;; flags: qr rd; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: recursion requested but not available

;; QUESTION SECTION:
;freespeechme.bit.		IN	A

;; Query time: 12 msec
;; SERVER: 127.0.0.1#5333(127.0.0.1)
;; WHEN: Thu May 07 22:03:58 EEST 2015
;; MSG SIZE  rcvd: 34

2015-05-07T18:57:17.220Z - debug: [DNS] creating bottleneck on: dns-127.0.0.1-freespeechme.bit (dns.coffee:75)
2015-05-07T18:57:17.223Z - debug: [DNS] received question 
{ name: 'freespeechme.bit',
  type: 1,
  class: 1 }
2015-05-07T18:57:17.224Z - debug: [DNS] resolving via namecoin... (<callback> dns.coffee:148) 
{ domain: 'freespeechme.bit',
  q: 
   { name: 'freespeechme.bit',
     type: 1,
     class: 1 } }
2015-05-07T18:57:17.227Z - debug: [NMC] namecoin resolve (<resources> namecoin.coffee:77) 
{ property: 'd/freespeechme' }
2015-05-07T18:57:17.248Z - debug: [DNS] namecoin resolved query (dns.coffee:161) 
{ q: 
   { name: 'freespeechme.bit',
     type: 1,
     class: 1 },
  d: 'freespeechme.bit',
  result: 
   { version: '0.0.1',
     header: { datastore: 'namecoin' },
     data: 
      { name: 'd/freespeechme',
        value: 
         { fingerprint: '00:94:93:86:DC:A9:0C:9F:B7:3E:D9:01:04:0A:92:99:9A:DE:97:1C',
           map: 
            { www: 
               { ip: '108.61.170.200',
                 ip6: '2001:19f0:6c00:8567::64' } },
           email: 'jeremy@veclabs.net',
           info: 'Viral Electron Chaos Laboratories' },
        txid: 'de0e53bc9e3bef74a62636a14cdeb7feaef961e5567622c801e33b0c2145d94b',
        address: 'MzzESs3XwEbY8v5gm9QZTNPe5oSv8eX5e7',
        expires_in: 31339 } } }
2015-05-07T18:57:17.267Z - debug: [NMC] A handler for namecoin (<BlockchainResolver> blockchain.coffee:149)
2015-05-07T18:57:17.273Z - warn: [NMC] no useful data from nmc_show (<BlockchainResolver> blockchain.coffee:243) 
{ q: 
   { name: 'freespeechme.bit',
     type: 1,
     class: 1 } }
2015-05-07T18:57:17.287Z - debug: [DNS]  (<sendErr> dns.coffee:269) 
{ code: 3, name: 'NOTFOUND' }

**Comment by taoeffect** [comment] 2015-05-08 04:57
This is a duplicate of #4. DNSChain doesn't yet support Namecoin's `map` notation.

**Closed** 2015-05-08 04:57 UTC
Labels: duplicate
